#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
bspc monitor eDP-1 -d I II III IV V &

~/.config/polybar/launch.sh &

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding 	 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on

export _JAVA_AWT_WM_NONREPARENTING=1ajosm

